languageCode: en
languageName: English
weight: 2
copyright: © 2016-{year} {name}
hasCJKLanguage: false
summaryLength: 120

author:
  name: Takuya Tokuda
  first_name: Takuya
  last_name: Tokuda
  gender: male
  email: cs.toku.mail+blog@gmail.com
  page: /about/

params:
  github: cstoku
  linkedin: takuya-tokuda-20969795
  googleplus: "114783483415550877902"
  email: cs.toku.mail+blog@gmail.com
  facebook:
    id: takuya.tokuda.0122
    uid: "100003789482934"
    appid: "1168458043296329"
  twitter:
    card_type: summary
    id: CS_Toku
    uid: "131178169"
  youtube: "UCqZ86iRrENKkWgjxJqBfVnQ"
  flattr: ""
  disqusIframeURL: https://disqus.cstoku.dev/
  maxTaxonomyContents: 5
  atomLimit: 15
  dateFormat: "Jan 2, 2006, 15:04 MST"
  description: "Write about daily learning, what I thought, etc..."
  locale: en_US
  themeColor: "#2ea9df"
  backgroundColor: "#ffffff"
