baseurl = "http://www.sce-toku.jp/"
title = "Toku's Blog"

DefaultContentLanguage = "ja"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Pagination
paginate = 10
paginatePath = "page"

# Pygment
pygmentsCodeFences = true
pygmentsOptions = ""
pygmentsStyle = "native"

buildDrafts = true

ignoreFiles = [ "\\.un~$" ]

[Permalinks]
post = "/blog/:year/:month/:day/:filename/"
slide = "/slide/:year/:filename/"

[taxonomies]
tag = "tags"
topic = "topics"

[author]
name = "CS_Toku"
email = "cs.toku.mail@gmail.com"


#
# All parameters below here are optional and can be mixed and matched.
#

[params.theme]
name = "cosmo"

[params]
# menu for changing language. This changes languages with js and stores the choice with the help of JavaScript in a Cookie. Then the path is rewritten with pathnamereplace.js. The name of the md files needs to have the same name for each language abbreviation to work correctly. Example: showcase.en.md and showcase.sv.md. It only works if DefaultContentLanguageInSubdir = true
switchlang = false
brandImage = ""
brand = ""
topline = "few words about your site"
footline = "code with <i class='fa fa-heart'></i>"

# Text for the top menu link, which goes to the root URL for the site.
# Default (if omitted) is "Home".
home = "home"

mathjax = "2.7.1" # cdnjs hosted version; empty string to disable mathjax

# Show a sidebar menu
showRightSidebar = true

# Google Analytics.
# googleAnalytics = "UA-71075507-1"

# Sidebar social links.
github = "cstoku"
bitbucket = ""
linkedin = "cs.toku.mail@gmail.com"
googleplus = "cs.toku.mail@gmail.com"
facebook = "takuya.tokuda.0122"
twitter = "CS_Toku"
youtube = ""
flattr = ""

[blackfriday]
taskList = true
smartypants = true
angledQuotes = true
fractions = false
smartDashes = true
latexDashes = true
hrefTargetBlank = false
plainIdAnchors = true
extensions = []
extensionmask = []

[Languages]
[Languages.ja]
languageCode = "ja"
weight = 1
copyright = "(c) 2016 Copyright my blog"

[[Languages.ja.menu.main]]
name = "About"
weight = 1
idjatifier = ""
url = "/"
pre = "<i class='fa fa-road'></i>"

# add  links to the bottom right corner.
# [[Languages.ja.menu.footer]]
# name = "Footer"
# pre = "<i>&middot;</i>"
# idjatifier = "footer"
# weight = 1
# url = "/footer/"

[Languages.en]
languageCode = "en"
weight = 1
copyright = "(c) 2016 Copyright my blog"

[[Languages.en.menu.main]]
name = "About"
weight = 1
identifier = ""
url = "/"
pre = "<i class='fa fa-road'></i>"

