#
# Hugo Parameters
#
baseURL: https://staging.cstoku.me
title: "Toku's Blog"

buildDrafts: false
buildFuture: false
buildExpired: false

defaultContentLanguage: ja
defaultContentLanguageInSubdir: false

enableGitInfo: true
enableRobotsTXT: false
enableEmoji: true

metaDataFormat: yaml

paginate: 10
paginatePath: "page"

pygmentsOptions: "linenos=table"
pygmentsCodefences: true
pygmentsUseClasses: true

ignoreFiles: [ "\\.un~$" ]

rssLimit: 15

disableKinds:
  - RSS
  - sitemap
  - robotsTXT
  - 404

taxonomies:
  tag: tags

author:
  name: Takuya Tokuda
  email: cs.toku.mail@gmail.com
  page: /about/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Post"
      url: "/posts/"
      weight: 2
    - name: "Slide"
      url: "/slides/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 3
    - name: "About"
      url: "/about/"
      weight: 4

#
# Markdown Processer(Blackfriday) Options
#
blackfriday:
  taskList: true
  smartypants: true
  smartypantsQuotesNBSP: false
  angledQuotes: true
  fractions: false
  smartDashes: true
  latexDashes: true
  hrefTargetBlank: false
  plainIDAnchors: true
  extensions: []
  extensionmask: []

#
# Output Formats
#
outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]

#
# Site Parameters
#
params:
  github: cstoku
  linkedin: cs.toku.mail@gmail.com
  googleplus: cs.toku.mail@gmail.com
  facebook:
    id: takuya.tokuda.0122
    uid: 100003789482934
    appid: 1168458043296329
  twitter:
    card_type: summary
    id: CS_Toku
    uid: 131178169
  youtube: ""
  flattr: ""
  searchConsole: "0000000000"
  googleAnalytics: UA-71075507-1
  disqusIframeURL: https://disqus.cstoku.me/
  maxTaxonomyContents: 5
  siteThumbnail: /images/blog-thumb.jpg
  robots: none

#
# Multilingual Settings
#
languageCode: ja
languages:
  en:
    languageCode: en
    languageName: English
    weight: 1
    copyright: © 2016-{year} {name}
    hasCJKLanguage: false
    summaryLength: 120

    params:
      dateFormat: "Jan 2, 2006, 15:04 MST"
      description: "Desc"
      locale: en_US

  ja:
    languageCode: ja
    languageName: Japanese
    weight: 2
    copyright: © 2016-{year} {name}
    hasCJKLanguage: true
    summaryLength: 120

    params:
      dateFormat: "2006/01/02 15:04"
      description: "デスク"
      locale: ja_JP
