baseurl = "http://www.sce-toku.jp/"
title = "Toku's Blog"

DefaultContentLanguage = "ja"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Pagination
paginate = 10
paginatePath = "page"

buildDrafts = true

ignoreFiles = [ "\\.un~$" ]

[Permalinks]
post = "/blog/:year/:month/:day/:filename/"
slide = "/slide/:year/:filename/"

[taxonomies]
tag = "tags"
topic = "topics"

[author]
name = "CS_Toku"
email = "cs.toku.mail@gmail.com"


#
# All parameters below here are optional and can be mixed and matched.
#

[params.theme]
name = "paper"

[params.popover]
# This is a highly configurable popover form.
enablepopover = true #enable or disable popover: true/false.
posturl = "https://zapier.com/hooks/catch/1227563/" # Your zapier post hook.
headerimage = "//placehold.it/1000x600"
expirecookie = 5 #show it again after number of days to visitors that has not subscribed.
cookiename = "mycookie1" #give the cookie a unique name variable (avoid spaces and strange characters).
signupheader = "Join Our Newsletter"
showmodaltimeout = 10000 #show popover modal after time interval in milliseconds.
mouseleave = true #show popover when mouse leaves window: true/false.
modalsize = "" #lg or sm. Empty is md. If phone is detected lg is used.
imagedescription = "Placeholder image for this popover modal optin form"
signuptext = "Signup today for free and be the first to get notified on new updates."
inputplaceholder = "Enter your email"
submitbutton = "Subscribe"
successmessage = "Thanks for your subscription!"
errormessage = "Submitting form failed!"
optin = true #opt-in: true/false

[params]
# menu for changing language. This changes languages with js and stores the choice with the help of JavaScript in a Cookie. Then the path is rewritten with pathnamereplace.js. The name of the md files needs to have the same name for each language abbreviation to work correctly. Example: showcase.en.md and showcase.sv.md. It only works if DefaultContentLanguageInSubdir = true
switchlang = false
# You can use markdown here.
brandImage = ""
brand = ""
topline = "few words about your site"
footline = "code with <i class='fa fa-heart'></i>"

# Text for the top menu link, which goes to the root URL for the site.
# Default (if omitted) is "Home".
home = "home"

mailmunchid = "" # Mailmunch site id
sumomeid = "" # Sumome id
mathjax = "2.7.1" # cdnjs hosted version; empty string to disable mathjax

# Show a sidebar menu
showRightSidebar = true
# Select a syntax highlight.
# Check the static/css/highlight directory for options.
highlight = "default"

# Google Analytics.
googleAnalytics = "Your Google Analytics tracking code"

# Sidebar social links.
github = "Myprofile" # Your Github profile ID
bitbucket = "" # Your Bitbucket profile ID
linkedin = "" # Your LinkedIn profile ID (from public URL)
googleplus = "Myprofile" # Your Google+ profile ID
facebook = "Myprofile" # Your Facebook profile ID
twitter = "Myprofile" # Your Twitter profile ID
youtube = ""  # Your Youtube channel ID
flattr = ""  # populate with your flattr uid

[blackfriday]
taskList = true
smartypants = true
angledQuotes = true
fractions = false
smartDashes = true
latexDashes = true
hrefTargetBlank = false
plainIdAnchors = true
extensions = []
extensionmask = []

[Languages]
[Languages.ja]
languageCode = "ja"
weight = 1
copyright = "(c) 2016 Copyright my blog"

[[Languages.ja.menu.main]]
name = "About"
weight = 1
idjatifier = ""
url = "/"
pre = "<i class='fa fa-road'></i>"

# add  links to the bottom right corner.
# [[Languages.ja.menu.footer]]
# name = "Footer"
# pre = "<i>&middot;</i>"
# idjatifier = "footer"
# weight = 1
# url = "/footer/"

[Languages.en]
languageCode = "en"
weight = 1
copyright = "(c) 2016 Copyright my blog"

[[Languages.en.menu.main]]
name = "About"
weight = 1
identifier = ""
url = "/"
pre = "<i class='fa fa-road'></i>"

