#
# Hugo Parameters
#
baseURL: http://localhost/
title: "Toku's Blog"

buildDrafts: true
buildFuture: true
buildExpired: true

defaultContentLanguage: ja
defaultContentLanguageInSubdir: false

enableGitInfo: true
enableRobotsTXT: false
enableEmoji: true

summaryLength: 70
metaDataFormat: yaml

paginate: 10
paginatePath: "page"

pygmentsOptions: "linenos=table"
pygmentsCodefences: true
pygmentsUseClasses: true

ignoreFiles: [ "\\.un~$" ]

rssLimit: 15

# dummy static folder
staticDir: dummy
disableKinds:
  - RSS
  - sitemap
  - robotsTXT
  - 404

taxonomies:
  tag: tags
  category: categories
  level: level

author:
  name: Takuya Tokuda
  email: cs.toku.mail@gmail.com
  page: /about/
  about:

#
# Markdown Processer(Blackfriday) Options
#
blackfriday:
  taskList: true
  smartypants: true
  smartypantsQuotesNBSP: false
  angledQuotes: true
  fractions: false
  smartDashes: true
  latexDashes: true
  hrefTargetBlank: false
  plainIDAnchors: true
  extensions: []
  extensionmask: []

#
# Output Formats
#
outputs:
  home: ["HTML", "RSS"]
  page: ["HTML", "AMP"]

#
# Multilingual Settings
#
languageCode: ja
languages:
  en:
    languageCode: en
    languageName: English
    weight: 1
    copyright: (c) 2016 Copyright my blog

    menu:
      main:
        - name: "About"
          url: "/"
          weight: 1

  ja:
    languageCode: ja
    languageName: Japanese
    weight: 2
    copyright: (c) 2016 Copyright my blog


    #menu:
    #  main:
    #    - name: About
    #      url: /
    #      weight: 1

#
# Site Parameters
#
params:
  github: cstoku
  linkedin: cs.toku.mail@gmail.com
  googleplus: cs.toku.mail@gmail.com
  facebook:
    id: takuya.tokuda.0122
    uid: 100003789482934
  twitter:
    card_type: summary
    id: CS_Toku
    uid: 131178169
  youtube: ""
  flattr: ""
  searchConsole: "0000000000"

  # Google Analytics.
  googleAnalytics: UA-71075507-1
