baseurl = "http://www.sce-toku.jp/"
languageCode = "ja"
title = "Toku's Blog"
canonifyurls = true
buildDrafts = true

ignoreFiles = [ "\\.un~$" ]

[Params]
  subtitle = "とあるエンジニアの備忘録"
  Author = "CS_Toku"

  environment = "dev"

[Permalinks]
  post = "/blog/:year/:month/:day/:filename/"
  slide = "/slide/:year/:filename/"
