[Settings]
ID = "cstoku-blog"

[build]
publish = "public"
command = """
yarn &&
yarn run webpack &&
hugo --gc --config $HUGO_CONFIG"""

[build.environment]
HUGO_VERSION = "0.42.1"

[context.production.environment]
HUGO_CONFIG = "config-prod.yaml"
NODE_ENV = "production"

[context.staging.environment]
HUGO_CONFIG = "config-stg.yaml"
NODE_ENV = "production"

[context.disqus]
command = "hugo"

[[redirects]]
from = "https://sce-toku.jp/*"
to = "https://cstoku.me/:splat"
status = 301

[[redirects]]
from = "https://www.sce-toku.jp/*"
to = "https://cstoku.me/:splat"
status = 301

[[redirects]]
from = "https://cstoku-blog.netlify.com/*"
to = "https://cstoku.me/:splat"
status = 301

