[Settings]
ID = "cstoku-blog"

[build]
command = """
yarn &&
yarn run webpack &&
hugo --gc &&
yarn run workbox generateSW workbox-config.ja.js
yarn run workbox generateSW workbox-config.en.js
"""

[build.environment]
HUGO_VERSION = "0.54.0"

[context.production.environment]
NODE_ENV = "production"

[context.staging.environment]
NODE_ENV = "production"

[context.branch-deploy]
command = """
yarn &&
yarn run webpack &&
hugo --gc -e $BRANCH &&
yarn run workbox generateSW workbox-config.ja.js
yarn run workbox generateSW workbox-config.en.js
"""

[context.deploy-preview]
command = """
yarn &&
yarn run webpack &&
sed -i "s|__BASE_URL__|$DEPLOY_PRIME_URL|" config/deploy-preview/languages.$TARGET_LANG.yaml &&
sed -i "s|__BASE_URL__|/|" config/deploy-preview/languages.*.yaml &&
hugo --gc -e $CONTEXT &&
yarn run workbox generateSW workbox-config.ja.js
yarn run workbox generateSW workbox-config.en.js
"""

