#
# Hugo Parameters
#
title: "Toku's Blog"

buildDrafts: true
buildFuture: true
buildExpired: true

defaultContentLanguage: ja
defaultContentLanguageInSubdir: true

enableGitInfo: true
enableRobotsTXT: true
enableEmoji: true

metaDataFormat: yaml

paginate: 10
paginatePath: "page"

pygmentsOptions: "linenos=table"
pygmentsCodefences: true
pygmentsUseClasses: true

ignoreFiles: [ "\\.un~$" ]

staticDir: static/global

taxonomies:
  tag: tags

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

imaging:
  resampleFilter: Lanczos
  quality: 85

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Post"
      url: "/posts/"
      weight: 2
    - name: "Slide"
      url: "/slides/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 3
    - name: "About"
      url: "/about/"
      weight: 4
    - name: "RSS Feed"
      url: "/index.xml"
      weight: 10
      identifier: feed

#
# Markdown Processer(Blackfriday) Options
#
blackfriday:
  taskList: true
  smartypants: true
  smartypantsQuotesNBSP: false
  angledQuotes: true
  fractions: false
  smartDashes: true
  latexDashes: true
  hrefTargetBlank: false
  plainIDAnchors: true
  extensions: []
  extensionmask: []

#
# Output Formats
#
mediaTypes:
  application/atom+xml:
    suffixes: ["xml"]

outputFormats:
  ATOM:
    name: atom
    mediaType: application/atom+xml
    isHTML: false
    isPlainText: true
    noUgly: true
  MF:
    name: mf
    baseName: manifest
    rel: manifest
    mediaType: application/json
    isHTML: false
    isPlainText: true
    noUgly: true

outputs:
  home: ["HTML", "ATOM", "MF"]
  page: ["HTML"]
  section: ["HTML"]
  taxonomyTerm: ["HTML"]
  taxonomy: ["HTML"]

#
# Multilingual Settings
#
languageCode: ja
languages:
  ja:
    languageCode: ja
    languageName: Japanese
    weight: 1
    baseURL: http://localhost:1313
    copyright: © 2016-{year} {name}
    hasCJKLanguage: true
    summaryLength: 120
    staticDir2: static/ja

    author:
      name: Takuya Tokuda
      first_name: Takuya
      last_name: Tokuda
      gender: male
      email: cs.toku.mail+blog@gmail.com
      page: /about/

    params:
      github: cstoku
      linkedin: takuya-tokuda-20969795
      googleplus: "114783483415550877902"
      email: cs.toku.mail+blog@gmail.com
      facebook:
        id: takuya.tokuda.0122
        uid: "100003789482934"
        appid: "1168458043296329"
      twitter:
        card_type: summary
        id: CS_Toku
        uid: "131178169"
      youtube: "UCqZ86iRrENKkWgjxJqBfVnQ"
      flattr: ""
      disqusIframeURL: https://disqus.cstoku.dev/
      maxTaxonomyContents: 5
      atomLimit: 15
      dateFormat: "2006/01/02 15:04"
      description: "日々の学びや思ったことなどなど、書いていきます。"
      locale: ja_JP
      themeColor: "#2ea9df"
      backgroundColor: "#ffffff"

  en:
    languageCode: en
    languageName: English
    weight: 2
    baseURL: http://localhost:1314
    copyright: © 2016-{year} {name}
    hasCJKLanguage: false
    summaryLength: 120
    staticDir2: static/en

    author:
      name: Takuya Tokuda
      first_name: Takuya
      last_name: Tokuda
      gender: male
      email: cs.toku.mail+blog@gmail.com
      page: /about/

    params:
      github: cstoku
      linkedin: takuya-tokuda-20969795
      googleplus: "114783483415550877902"
      email: cs.toku.mail+blog@gmail.com
      facebook:
        id: takuya.tokuda.0122
        uid: "100003789482934"
        appid: "1168458043296329"
      twitter:
        card_type: summary
        id: CS_Toku
        uid: "131178169"
      youtube: "UCqZ86iRrENKkWgjxJqBfVnQ"
      flattr: ""
      disqusIframeURL: https://disqus.cstoku.dev/
      maxTaxonomyContents: 5
      atomLimit: 15
      dateFormat: "Jan 2, 2006, 15:04 MST"
      description: "Write about daily learning, what I thought, etc..."
      locale: en_US
      themeColor: "#2ea9df"
      backgroundColor: "#ffffff"
